### ISSUE TITLE
`RolesExtractor.extract()` does not list the roles correctly

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#88]
On our latest build of Marker Data, when drag and drop timeline into Roles Workflow Extension, it does not list the roles correctly.

https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-1914549540

**Comment by orchetect** [comment]
I need the FCP project for this.

**Comment by IAmVigneswaran** [comment]
> I need the FCP project for this.

Here is the test project.

[Test.fcpbundle.zip](https://github.com/TheAcharya/MarkersExtractor/files/14091805/Test.fcpbundle.zip)

Thank you.

**Comment by IAmVigneswaran** [comment]
Related with #90

For Audio only timeline, the extract Video Role is shown. Maybe like #91, we can keep `Video Role & Subrole` empty where there no assign or not applicable

<img width="997" alt="audio-only-01" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/3f9768ff-755a-429c-a7fe-4f80a6dce48f">

Also, I noticed that the `Effect` Roles is not shown correctly.

**Comment by orchetect** [comment]
Found the culprit - there was a bug in the FCPXML parser when reading the `role` attribute from `title` elements and it was reading the wrong attribute.

Roles extraction should work correctly now.

**Comment by orchetect** [comment]
I haven't tested an audio-only timeline yet.

re: Effects, I don't know what's going on there. I processed a large project that had the role and it was parsed out as `Effects.Effects-1`.

**Comment by IAmVigneswaran** [comment]
> I haven't tested an audio-only timeline yet.

[Audio Only_01.fcpxmld.zip](https://github.com/TheAcharya/MarkersExtractor/files/15087679/Audio.Only_01.fcpxmld.zip)

Here is a sample timeline for your test.

I think `Effects.Effects-1` is normal.

**Comment by orchetect** [comment]
> Audio Only_01.fcpxmld.zip

btw, FCP refused to import this file saying it failed the DTD check. I had to open it in a text editor and fix the modDate which contained some odd characters.

I noticed that FCP shows the Effects role as `Effects-1` for this project, but the XML itself only contains `"effects"` as the audio role name. I think FCP is using shorthand for some built-in roles knowing that it auto-generates the implicit `-1` role in this case, instead of actually writing `effects.effects-1` to the XML. This definitely complicates things if we want to try and mirror what FCP is showing. But functionally it should still work since at least it can be used to filter roles.

```xml
<asset-clip ref="r2" offset="0s" name="Forest Day" duration="1550549/24000s" audioRole="effects">
```

Whereas some so-called default roles are written in full to the XML:

```xml
<audio-channel-source srcCh="1, 2" role="music.music-1"/>
```

**Comment by orchetect** [comment]
> For Audio only timeline, the extract Video Role is shown

Ok this is now fixed in DAWFileKit. It was erroneously injecting the Video role automatically for `asset-clip`s but shouldn't now.

**Comment by IAmVigneswaran** [comment]
Seems like the issue still persist. For some reason, video role is not listed?

Here is the FCPXML.

[Roles Demo.fcpxmld.zip](https://github.com/TheAcharya/MarkersExtractor/files/15157163/Roles.Demo.fcpxmld.zip)

<img width="500" alt="Roles-Bugs" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/28057a3b-8fa4-419f-85e9-f7bfb5f4cc6b">

**Comment by IAmVigneswaran** [comment]
My bad! 

I realise that the "Video" role can only be shown when the clips on are assign a video Role.  When video Role is not assigned, it is defaults to the Dialogue Role. Which is the correct behaviour. 

<img width="564" alt="Roles-Test" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/4ba9f802-4b51-4581-b360-60f5e464213b">
